### ISSUE TITLE
Filemanger crash browsing network

### ISSUE THREAD

**Issue by bluethumb** [ubports/filemanager-app#1]
Using on M10FHD the filemanger it crashes when I try browsing the network

**Comment by Flohack74** [comment]
Did this ever work? I never tried on the old images. I also do not see any method / setting for specifying samba parameters like comuter or domain name...

**Comment by arubislander** [comment]
I am not sure if it ever worked in the official images. I know for sure it wasn't working in the last couple of OTA's from Canonical.
However I did see this work in an unofficial version of the filemanager app unofficial that was uploaded to the openstore by @popey back in the day.

**Comment by nfsprodriver** [comment]
Seems to fixed with #7

**Comment by bluethumb** [comment]
Hmm.. just installed r2 (20170923) and filemanager now shows a "running" circle and the crash !? So I guess no fix yet this is on a bq M10FHD

**Comment by sverzegnassi** [comment]
The fix hasn't been released yet - but it's included in the development version of FM which will be available soon, I guess

**Comment by bluethumb** [comment]
Nice, all thougt I run "stable"

**Comment by nfsprodriver** [comment]
Fix released, but we may investigate into samba stuff. See #28

**Comment by tjrhodes** [comment]
Device: FP2
System Build: 2018-W48

No crash, but I can't mount a smb share over the network, I can't see where to put the address and after the spinning circle I get no files but there are samba shares on the network and a windows network too.

**Comment by WillemHexspoor** [comment]
Device: Mako
System build: 2018-w48

After installing cifs-utils with apt, I'm able to successfully mount a smb share at the command line. The file manager is able to read and write to the share without crashing. The ssh connection, which i used to access the shell, was very slow the first moments after mounting.

**Comment by tm-s** [comment]
Device: M10FHD
System build: 2018-w48

- opening filemanager
- browsing through network
- establishing a smb connection by providing credentials when prompted by the filemanager

result: works without any issues, remote items are displayed as expected, smb connection is fine

- bookmarking a smb folder in the filemanager
- closing and reopening the filemanager
- selecting the smb bookmark

result: works without any issues, remote items are displayed as expected

- removing the bookmark
- browsing again through the network without reopening the filemanager

result: works without any issues, remote items are displayed as expected

works for me :-)

cheers
