### ISSUE TITLE
Simplify building process

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/filemanager-app#11]
Building this is a pain in the ass!

It would be nice to reduce the necessary scripts to one and maybe adopt clickable for building.

**Comment by sverzegnassi** [comment]
Will have a look at this, would be great if we could migrate to QMake (even if it requires special scripts in order to download dependencies that are not available on UT)

**Comment by nfsprodriver** [comment]
Build works now by simply running clickable. The container issues have been fixed ;)
