### ISSUE TITLE
cut and select all

### ISSUE THREAD

**Issue by bqphone** [ubports/filemanager-app#3]
It would be great if file manager has those options added, it will help alot in managing files movement between the phone and sd card.

**Comment by nfsprodriver** [comment]
Multiple file management (not folders yet) included in #7

**Comment by nfsprodriver** [comment]
Finished work on that. Should be in the dev version of the filemanager-app in the OpenStore. Going to close this when in final...

**Comment by NeoTheThird** [comment]
Fixed in #14
