### ISSUE TITLE
SD-card content not displayed

### ISSUE THREAD

**Issue by hoh61** [ubports/filemanager-app#35]
Device: frieza
System: 16.04/devel
Version: r77

An external device is shown in the left indicator bar, the ID is correctly dislayed in the headline after selecting this card, but the content of the card is not displayed.

it can be seen using the shell (internal or adb) and with the USB cable connected to a PC.

**Comment by nfsprodriver** [comment]
I tested it after the big update and it works. If it still persist for you, you can reopen the issue. Thank you ;)

**Comment by hoh61** [comment]
I was wondering first, but then I noticed that the default view for your app is the home directory only (without the folder sidebar).
I would prefer at least an option to start in one of these views.
Most important: it works as expected!

**Comment by UniversalSuperBox** [comment]
I'm able to view the content on an SD card plugged in using a USB card reader on the Nexus 5 and Nexus 7 (flo). I'm able to view the content on an SD card in the slot on the Fairphone 2.

**Comment by hsbyter** [comment]
Fixed in 2018-w48 on m10 FHD
Im able to view content and play music from the SD-Card
