### ISSUE TITLE
Enchancement : need a search function in file manager

### ISSUE THREAD

**Issue by impressstudio** [ubports/filemanager-app#41]
Apps like Bluetooth file transfer and audio recorder saves file in some where else 

It would be handy if file manager has search bar or function

**Comment by UniversalSuperBox** [comment]
Fixed by https://gitlab.com/ubports/apps/filemanager-app/-/merge_requests/89

To the person who posted the bounty on this issue: Please note that we have no control over our page on BountySource, and while it may work we have no guarantees that will continue.
