### ISSUE TITLE
Filemanager can't save files from Telegram app

### ISSUE THREAD

**Issue by advocatux** [ubports/filemanager-app#48]
### Device & OS
Tested in a BQ E4.5 running UT 16.04 (2018-09-19) but I think this issue affects all devices.

### Apps version number
* Telegram: 2.5.4.0
* File Manager: 0.6.0

### Steps to reproduce
Try to copy a downloaded file from Telegram app to File Manager

### Expected behavior
The file is copied

### Actual behavior
The copy fails without any visible error message

### Logfiles
These are the File Manager logs when trying to copy an mp3 file (`SampleAudio_0.4mb.mp3`):
* With File Manager closed and not authenticated previously https://paste.ubuntu.com/p/hWsW7mcGTT/
* With File Manager already open and authenticated previously https://paste.ubuntu.com/p/S5ScTsGSc2/

**Comment by tjrhodes** [comment]
Device: FP2
System Build: 2018-W48

Issue remains, cannot save a photo from telegram locally, either by using the download option or through Share > File Manager. I select the folder to download/copy to but then it fails silently.

**Comment by UniversalSuperBox** [comment]
Looks like the update hasn't been released yet. I'll remove this from the tracker.
