### ISSUE TITLE
 Unzip action need a progressbar

### ISSUE THREAD

**Issue by xqqy** [ubports/filemanager-app#57]
Description of the feature

Now, when unzipping, it only shows a unknown length of progressbar. When unzipping take a lot of time, this feel really bad. Because of unknown time.
It is easy to set how many file are already unzipped and how many a the rest. And a progressbar for known time is great.

**Comment by Flohack74** [comment]
I am not aware of any progress bar that is existing in filemanager-app. What operating system do you have?

**Comment by xqqy** [comment]
![978screenshot20181105_065440538](https://user-images.githubusercontent.com/28598660/47991184-6b4bc480-e124-11e8-8c69-5a5cfff27899.png)
In this picture. 
Here should have a progress bar shows how much are extracted.

**Comment by Flohack74** [comment]
Ok thx! Now its clear.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/apps/filemanager-app/-/issues/57
