### ISSUE TITLE
Can't dowload from WebTelegram.

### ISSUE THREAD

**Issue by CesarHerreraG** [ubports/filemanager-app#64]
And with Telegram the same problem.

**Comment by mihaelmilea** [comment]
I don't understand very well what you are saying and I want to open an issue about not being able to save an attachment from Dekko but it might be the same issue - so, is it?: I select to open the attachment from Dekko with FileManager and then I select a folder, I see that it displays a text "save it to this location" and, when I click "select", the "save it here", "select" and "cancel" buttons dissapear but nothing was really saved.

**Comment by CesarHerreraG** [comment]
In WebTelegram I see a file to download. I push download and after a time it says "save file". (In this case it was a photo). It shows this:

**Comment by CesarHerreraG** [comment]
No. It does nothing.

**Comment by mihaelmilea** [comment]
Then what is the connection between Telegram and FileManager?

**Comment by CesarHerreraG** [comment]
The problem is before accessing File Manager. In fact WebTelegram doesn't start File Manager.

**Comment by CesarHerreraG** [comment]
When I writed this isue it was different. It appeared Filemanager but it did nothing when I pushed the button. Now the File manager is not appearing. I have a photo of what it gives but O don't know to put it here and now Dekko doesn't allow me to send it :(

**Comment by CesarHerreraG** [comment]
In the past it appeared but did not allow me to download the file. It's curious that now File Manager doesn't appear. So it impossible to download the file.

**Comment by CesarHerreraG** [comment]
________________________________________
De: Mihael Milea <notifications@github.com>
Enviado: viernes, 4 de enero de 2019 0:31
Para: ubports/filemanager-app
Cc: CesarHerreraG; Author
Asunto: Re: [ubports/filemanager-app] Can't dowload from WebTelegram. (#64)

Then what is the connection between Telegram and FileManager?

**Comment by mihaelmilea** [comment]
Ok, looks like an update has been built but not released yet to the OpenStore: https://github.com/ubports/filemanager-app/issues/48 - is this the same issue you are having?

**Comment by CesarHerreraG** [comment]
Yes, it is.

**Comment by CesarHerreraG** [comment]
I close the threat as it is in "64".
