### ISSUE TITLE
It is not possible to open PDF with the document viewer

### ISSUE THREAD

**Issue by j2g2rp** [ubports/filemanager-app#66]
If I try to open a pdf file through file manager document viewer is not listed in open with option. I just can "use" "openStore" .
I'm not sure if it's related to file manager or not but if i download the pdf and open it trough morph browser document viewer is listed and i can open it.

**Comment by Anne017** [comment]
Have you tried this?
Install the [Document Viewer](https://open-store.io/app/com.ubuntu.docviewer) app.
Navigate to the right folder with the file manager and tap on the PDF file.
Choose the "Open with another app" option in the [Content Hub](http://docs.ubports.com/en/latest/appdev/guides/contenthub.html) then Document Viewer.

It opens the document for me (config: Fairphone 2, 16.04, OTA 7, rc).

**Comment by j2g2rp** [comment]
Sure but just openStore is listed in content hub.

Is listed for you? It couldbe a problem just with E4.5?

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/apps/filemanager-app/-/issues/66
